---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: "Include {{ role_namespace }}.{{ role_name }}"
      ansible.builtin.include_role:
        name: "{{ role_namespace }}.{{ role_name }}"
